version: "3"
services:
  redis_app:
    image: "redis:4.0"
    container_name: redis_app
    ports:
      - "6379"
    volumes:
      - redis_data:/data
      
  postgres:
    image: "postgres:12"
    container_name: postgres
    ports:
      - "54321:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db_data:/var/lib/postgresql/data:delegated
      - shared_data:/var/shared
  app:
    build:
      args:
        RUBY_VERSION: '3.0.1'
        NODE_MAJOR: '14'
        BUNDLE_VERSION: '2.2.15'
      context: .
      dockerfile: Dockerfile.dev
    container_name: app
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432
    volumes:
      - .:/app:cached
      - rails_cache:/app/tmp/cache
      - bundle:/usr/local/bundle
      - node_modules:/app/node_modules
      - gem_cache:/usr/local/bundle/gems
    ports:
      - "3001:3000"
    command: ./dev-docker-entrypoint.sh
    depends_on:
      - postgres
      - redis_app
  workers:
    build:
      args:
        RUBY_VERSION: '3.0.1'
        NODE_MAJOR: '14'
        BUNDLE_VERSION: '2.2.15'
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app:cached
      - rails_cache:/app/tmp/cache
      - bundle:/usr/local/bundle
      - node_modules:/app/node_modules
      - gem_cache:/usr/local/bundle/gems
    command: bundle exec rails environment resque:work
    environment:
      - REDIS_URL=redis://redis_app:6379
      - QUEUE=*
    depends_on:
      - app

volumes:
  rails_cache:
  bundle:
  node_modules:
  gem_cache:
  db_data:
  shared_data:
  redis_data:
