version: "3.8"

services:
  postgres:
    image: postgres:14-alpine
    volumes:
      - postgres:/var/lib/potsgresql/data:delegated
    ports:
      - 54321:5432
    env_file:
      - .env.development

volumes:
  postgres: