version: "3"
volumes:
  db_data:
  gem_cache:
  shared_data:
  packs:
services:
  db:
    image: "postgres:13.5-alpine"
    container_name: db
    ports:
      - "54321:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db_data:/var/lib/postgresql/data:delegated
      - shared_data:/var/shared
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: web
    entrypoint: dev-docker-entrypoint.sh
    volumes:
      - ./:/app
      - packs:/app/public/packs
      - shared_data:/var/shared
      - gem_cache:/usr/local/bundle/gems
    ports:
      - "3000:3000"
    command: ["rails", "server", "-p", "3000", "-b", "0.0.0.0"]
    environment:
      RAILS_ENV: development
    depends_on:
      - db
