# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: ry
  password: secret

# development:
#   <<: *default
#   database: prototype_kak_dev

# local windows ( laptop )
#development:
#  <<: *default
#  username: postgres
#  password: nsgt88
#  port: 5433
#  database: prototype_kak_dev
docker: &docker
  <<: *default
  host: db
  username: postgres
  password: postgres
  port: 5432

#docker
development:
  <<: *docker
  database: prototype_kak_dev

test:
  <<: *docker
  database: prototype_kak_test

production:
  <<: *docker
  database: prototype_kak_prod
#end docker

# test:
#   <<: *default
#   database: prototype_kak_test

# production:
#   <<: *default
#   database: prototype_kak_prod
